apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesentiment-api
  labels:
    app: moviesentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviesentiment
  template:
    metadata:
      labels:
        app: moviesentiment
    spec:
      containers:
        - name: api
          image: "<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPO>:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: CAPSTONE_TEST
              valueFrom:
                secretKeyRef:
                  name: capstone-secret
                  key: CAPSTONE_TEST
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: moviesentiment-service
spec:
  type: LoadBalancer
  selector:
    app: moviesentiment
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000