apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesentiment
  labels:
    app: moviesentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviesentiment
  template:
    metadata:
      labels:
        app: moviesentiment
    spec:
      containers:
      - name: moviesentiment
        image: 970688244781.dkr.ecr.us-east-1.amazonaws.com/moviesentiment:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: CAPSTONE_TEST
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: moviesentiment-service
spec:
  type: LoadBalancer
  selector:
    app: moviesentiment
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000